# .github/workflows/daily.yml
name: TYPE SANIA Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: write  # Required to push commits

jobs:
  commit-sania:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run SANIA pixel day commit script
        run: python commit_if_pixel_day.py

      - name: Push changes
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to push"
          else
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}